<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InitialDataSeeder extends Seeder
{
    public function run(): void
    {
        

        // ==================== LUGARES ====================
        DB::table('lugares')->insert([
            [
                'nombre' => 'Castillo de la Glorieta',
                'descripcion' => 'Antiguo castillo con arquitectura europea y toques románticos, uno de los íconos turísticos de Sucre.',
                'direccion' => 'Carretera a Yotala',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/glorieta.jpg',
                'rating' => 4.5,
                'imagenes' => json_encode([
                    'assets/lugares/glorieta1.jpg',
                    'assets/lugares/glorieta2.jpg',
                    'assets/lugares/glorieta3.jpg',
                    'assets/lugares/glorieta4.jpg',
                ]),
                'horario' => '08:00 - 18:00',
                'latitud' => -19.0790,
                'longitud' => -65.2625,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mirador de la Recoleta',
                'descripcion' => 'Mirador tradicional con vista panorámica de toda la ciudad de Sucre.',
                'direccion' => 'Barrio Recoleta',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/recoleta.jpg',
                'rating' => 4.7,
                'imagenes' => json_encode([
                    'assets/lugares/recoleta1.jpg',
                    'assets/lugares/recoleta2.jpg',
                    'assets/lugares/recoleta3.jpg',
                    'assets/lugares/recoleta4.jpg',
                ]),
                'horario' => '07:00 - 22:00',
                'latitud' => -19.0502,
                'longitud' => -65.2590,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Museo de Arte Indígena ASUR',
                'descripcion' => 'Museo especializado en textiles y arte indígena de las culturas andinas.',
                'direccion' => 'Calle Iturricha',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/asur.jpg',
                'rating' => 4.8,
                'imagenes' => json_encode([
                    'assets/lugares/asur1.jpg',
                    'assets/lugares/asur2.jpg',
                    'assets/lugares/asur3.jpg',
                    'assets/lugares/asur4.jpg',
                ]),
                'horario' => '09:00 - 18:00',
                'latitud' => -19.0470,
                'longitud' => -65.2540,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Casa de la Libertad',
                'descripcion' => 'Lugar histórico donde se firmó el Acta de la Independencia de Bolivia.',
                'direccion' => 'Plaza 25 de Mayo',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/casa_libertad.jpg',
                'rating' => 4.9,
                'imagenes' => json_encode([
                    'assets/lugares/casa_libertad1.jpg',
                    'assets/lugares/casa_libertad2.jpg',
                    'assets/lugares/casa_libertad3.jpg',
                    'assets/lugares/casa_libertad4.jpg',
                ]),
                'horario' => '09:00 - 19:00',
                'latitud' => -19.0476,
                'longitud' => -65.2601,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Catedral Metropolitana',
                'descripcion' => 'Imponente catedral colonial ubicada frente a la plaza principal.',
                'direccion' => 'Plaza 25 de Mayo',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/catedral.jpg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/lugares/catedral1.jpg',
                    'assets/lugares/catedral2.jpg',
                    'assets/lugares/catedral3.jpg',
                    'assets/lugares/catedral4.jpg',
                ]),
                'horario' => '07:00 - 20:00',
                'latitud' => -19.0474,
                'longitud' => -65.2597,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Museo del Tesoro',
                'descripcion' => 'Museo sobre la historia minera y joyas de Bolivia.',
                'direccion' => 'Calle Nicolás Ortiz',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/tesoro.jpg',
                'rating' => 4.5,
                'imagenes' => json_encode([
                    'assets/lugares/tesoro1.jpg',
                    'assets/lugares/tesoro2.jpg',
                    'assets/lugares/tesoro3.jpg',
                    'assets/lugares/tesoro4.jpg',
                ]),
                'horario' => '09:30 - 18:30',
                'latitud' => -19.0481,
                'longitud' => -65.2608,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Convento San Felipe Neri',
                'descripcion' => 'Convento colonial con acceso a las azoteas y vistas únicas.',
                'direccion' => 'Calle Nicolás Ortiz',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/san_felipe.jpeg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/lugares/san_felipe1.jpeg',
                    'assets/lugares/san_felipe2.jpeg',
                    'assets/lugares/san_felipe3.jpeg',
                    'assets/lugares/san_felipe4.jpeg',
                ]),
                'horario' => '09:00 - 18:00',
                'latitud' => -19.0485,
                'longitud' => -65.2622,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Museo Etnográfico',
                'descripcion' => 'Muestra de culturas, trajes y tradiciones de Bolivia.',
                'direccion' => 'Zona Central',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/etnografico.jpeg',
                'rating' => 4.4,
                'imagenes' => json_encode([
                    'assets/lugares/etnografico1.jpeg',
                    'assets/lugares/etnografico2.jpeg',
                    'assets/lugares/etnografico3.jpeg',
                    'assets/lugares/etnografico4.jpeg',
                ]),
                'horario' => '09:00 - 17:00',
                'latitud' => -19.0460,
                'longitud' => -65.2580,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Museo Militar',
                'descripcion' => 'Museo dedicado a la historia militar boliviana.',
                'direccion' => 'Zona Central',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/museo_militar.jpeg',
                'rating' => 4.1,
                'imagenes' => json_encode([
                    'assets/lugares/museo_militar1.jpeg',
                    'assets/lugares/museo_militar2.jpeg',
                    'assets/lugares/museo_militar3.jpeg',
                    'assets/lugares/museo_militar4.jpeg',
                ]),
                'horario' => '09:00 - 17:00',
                'latitud' => -19.0520,
                'longitud' => -65.2610,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mirador San Miguel',
                'descripcion' => 'Mirador menos concurrido con hermosas vistas de la ciudad.',
                'direccion' => 'Barrio San Miguel',
                'categoria' => 'caro',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/san_miguel.jpeg',
                'rating' => 4.3,
                'imagenes' => json_encode([
                    'assets/lugares/san_miguel1.jpeg',
                    'assets/lugares/san_miguel2.jpeg',
                    'assets/lugares/san_miguel3.jpeg',
                    'assets/lugares/san_miguel4.jpeg',
                ]),
                'horario' => '08:00 - 21:00',
                'latitud' => -19.0550,
                'longitud' => -65.2650,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ECONÓMICOS
            [
                'nombre' => 'Parque Bolívar',
                'descripcion' => 'Parque emblemático ideal para paseos, deporte y descanso.',
                'direccion' => 'Zona Central',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/bolivar.jpg',
                'rating' => 4.2,
                'imagenes' => json_encode([
                    'assets/lugares/bolivar1.jpg',
                    'assets/lugares/bolivar2.jpg',
                    'assets/lugares/bolivar3.jpg',
                    'assets/lugares/bolivar4.jpg',
                ]),
                'horario' => '06:00 - 22:00',
                'latitud' => -19.0468,
                'longitud' => -65.2575,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Parque Cretácico',
                'descripcion' => 'Parque temático con huellas de dinosaurios y miradores.',
                'direccion' => 'Zona de Fancesa',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/cretacico.jpg',
                'rating' => 4.3,
                'imagenes' => json_encode([
                    'assets/lugares/cretacico1.jpg',
                    'assets/lugares/cretacico2.jpg',
                    'assets/lugares/cretacico3.jpg',
                    'assets/lugares/cretacico4.jpg',
                ]),
                'horario' => '08:30 - 17:30',
                'latitud' => -19.0400,
                'longitud' => -65.2700,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'La Rotonda',
                'descripcion' => 'Plaza tranquila ideal para tomar un helado o descansar.',
                'direccion' => 'Av. Venezuela',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/rotonda.jpg',
                'rating' => 4.1,
                'imagenes' => json_encode([
                    'assets/lugares/rotonda1.jpg',
                    'assets/lugares/rotonda2.jpg',
                    'assets/lugares/rotonda3.jpg',
                    'assets/lugares/rotonda4.jpg',
                ]),
                'horario' => '24 horas',
                'latitud' => -19.0300,
                'longitud' => -65.2550,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mercado Central',
                'descripcion' => 'Mercado tradicional con comida, frutas y productos típicos.',
                'direccion' => 'Zona Central',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/mercado_central.jpeg',
                'rating' => 4.4,
                'imagenes' => json_encode([
                    'assets/lugares/mercado_central1.jpeg',
                    'assets/lugares/mercado_central2.jpeg',
                    'assets/lugares/mercado_central3.jpeg',
                    'assets/lugares/mercado_central4.jpeg',
                ]),
                'horario' => '07:00 - 19:00',
                'latitud' => -19.0490,
                'longitud' => -65.2590,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mercado Campesino',
                'descripcion' => 'Mercado grande con productos frescos y ropa a buen precio.',
                'direccion' => 'Zona Campesino',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/mercado_campesino.jpeg',
                'rating' => 4.0,
                'imagenes' => json_encode([
                    'assets/lugares/mercado_campesino1.jpeg',
                    'assets/lugares/mercado_campesino2.jpeg',
                    'assets/lugares/mercado_campesino3.jpeg',
                    'assets/lugares/mercado_campesino4.jpeg',
                ]),
                'horario' => '07:00 - 20:00',
                'latitud' => -19.0600,
                'longitud' => -65.2630,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Plaza 25 de Mayo',
                'descripcion' => 'Plaza principal de Sucre, rodeada de edificios históricos.',
                'direccion' => 'Centro de la ciudad',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/plaza25.jpeg',
                'rating' => 4.8,
                'imagenes' => json_encode([
                    'assets/lugares/plaza25_1.jpeg',
                    'assets/lugares/plaza25_2.jpeg',
                    'assets/lugares/plaza25_3.jpeg',
                    'assets/lugares/plaza25_4.jpeg',
                ]),
                'horario' => '24 horas',
                'latitud' => -19.0475,
                'longitud' => -65.2600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Plazuela Aniceto Arce',
                'descripcion' => 'Espacio tranquilo con árboles y bancos para descansar.',
                'direccion' => 'Zona Central',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/aniceto_arce.jpg',
                'rating' => 4.1,
                'imagenes' => json_encode([
                    'assets/lugares/aniceto_arce1.jpg',
                    'assets/lugares/aniceto_arce2.jpg',
                    'assets/lugares/aniceto_arce3.jpg',
                    'assets/lugares/aniceto_arce4.jpg',
                ]),
                'horario' => '24 horas',
                'latitud' => -19.0495,
                'longitud' => -65.2615,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Parque Infantil',
                'descripcion' => 'Parque con juegos para niños y áreas verdes.',
                'direccion' => 'Zona Norte',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/parque_infantil.jpg',
                'rating' => 4.0,
                'imagenes' => json_encode([
                    'assets/lugares/parque_infantil1.jpg',
                    'assets/lugares/parque_infantil2.jpg',
                    'assets/lugares/parque_infantil3.jpg',
                    'assets/lugares/parque_infantil4.jpg',
                ]),
                'horario' => '08:00 - 20:00',
                'latitud' => -19.0350,
                'longitud' => -65.2520,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Río Chico - Zona Recreativa',
                'descripcion' => 'Área natural cercana al río para paseos y picnic.',
                'direccion' => 'Camino a Río Chico',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/rio_chico.jpg',
                'rating' => 3.9,
                'imagenes' => json_encode([
                    'assets/lugares/rio_chico1.jpg',
                    'assets/lugares/rio_chico2.jpg',
                    'assets/lugares/rio_chico3.jpg',
                    'assets/lugares/rio_chico4.jpg',
                ]),
                'horario' => '08:00 - 18:00',
                'latitud' => -19.0700,
                'longitud' => -65.2800,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Cancha Deportiva Max Toledo',
                'descripcion' => 'Cancha multiuso para fútbol y otros deportes.',
                'direccion' => 'Zona Max Toledo',
                'categoria' => 'economico',
                'tipo' => 'lugar',
                'imagenAsset' => 'assets/lugares/max_toledo.jpg',
                'rating' => 4.0,
                'imagenes' => json_encode([
                    'assets/lugares/max_toledo1.jpg',
                    'assets/lugares/max_toledo2.jpg',
                    'assets/lugares/max_toledo3.jpg',
                    'assets/lugares/max_toledo4.jpg',
                ]),
                'horario' => '08:00 - 23:00',
                'latitud' => -19.0305,
                'longitud' => -65.2480,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ==================== RESTAURANTES ====================
        DB::table('restaurantes')->insert([
            [
                'nombre' => 'La Taverne',
                'descripcion' => 'Restaurante gourmet francés-boliviano con uno de los menús más elegantes de Sucre.',
                'direccion' => 'Calle Bolivar 490, Zona Central',
                'precio' => 'alto',
                'imagenAsset' => 'assets/restaurantes/la_taverne1.jpg',
                'rating' => 4.7,
                'imagenes' => json_encode([
                    'assets/restaurantes/la_taverne1.jpg',
                    'assets/restaurantes/la_taverne2.jpg',
                    'assets/restaurantes/la_taverne3.jpg',
                    'assets/restaurantes/la_taverne4.jpg',
                ]),
                'horario' => '12:00 - 22:00',
                'latitud' => -19.047019,
                'longitud' => -65.259563,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'El Huerto',
                'descripcion' => 'Restaurante de alta cocina con jardines amplios y ambiente elegante.',
                'direccion' => 'Calle J.M. Serrano 234',
                'precio' => 'alto',
                'imagenAsset' => 'assets/restaurantes/el_huerto1.jpg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/restaurantes/el_huerto1.jpg',
                    'assets/restaurantes/el_huerto2.jpg',
                    'assets/restaurantes/el_huerto3.jpg',
                    'assets/restaurantes/el_huerto4.jpg',
                ]),
                'horario' => '12:00 - 23:00',
                'latitud' => -19.045250,
                'longitud' => -65.255920,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Café Gourmet Mirador',
                'descripcion' => 'Restaurante con vista panorámica, platos internacionales y café de especialidad.',
                'direccion' => 'Camino a La Recoleta',
                'precio' => 'alto',
                'imagenAsset' => 'assets/restaurantes/gourmet_mirador1.jpg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/restaurantes/gourmet_mirador1.jpg',
                    'assets/restaurantes/gourmet_mirador2.jpg',
                    'assets/restaurantes/gourmet_mirador3.jpg',
                    'assets/restaurantes/gourmet_mirador4.jpg',
                ]),
                'horario' => '11:00 - 23:00',
                'latitud' => -19.050380,
                'longitud' => -65.259500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'La Vieja Bodega',
                'descripcion' => 'Cocina gourmet y selecta oferta de vinos en un ambiente colonial.',
                'direccion' => 'La Recoleta',
                'precio' => 'alto',
                'imagenAsset' => 'assets/restaurantes/vieja_bodega1.jpg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/restaurantes/vieja_bodega1.jpg',
                    'assets/restaurantes/vieja_bodega2.jpg',
                    'assets/restaurantes/vieja_bodega3.jpg',
                    'assets/restaurantes/vieja_bodega4.jpg',
                ]),
                'horario' => '12:00 - 22:00',
                'latitud' => -19.051200,
                'longitud' => -65.260900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Japo Sushi Premium',
                'descripcion' => 'Restaurante de sushi premium y cocina fusión japonesa.',
                'direccion' => 'Avenida Hernando Siles',
                'precio' => 'alto',
                'imagenAsset' => 'assets/restaurantes/japo_sushi1.jpg',
                'rating' => 4.5,
                'imagenes' => json_encode([
                    'assets/restaurantes/japo_sushi1.jpg',
                    'assets/restaurantes/japo_sushi2.jpg',
                    'assets/restaurantes/japo_sushi3.jpg',
                    'assets/restaurantes/japo_sushi4.jpg',
                ]),
                'horario' => '12:00 - 23:00',
                'latitud' => -19.038410,
                'longitud' => -65.255881,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // GastroBar El Mercado (está en bares y restaurantes en tu data, lo dejamos aquí también)
            [
                'nombre' => 'Café Gourmet Mirador',
                'descripcion' => 'Café gourmet con vista panorámica a toda la ciudad.',
                'direccion' => 'La Recoleta',
                'precio' => 'alto',
                'imagenAsset' => 'assets/restaurantes/gourmet_mirador.jpg',
                'rating' => 4.8,
                'imagenes' => json_encode([
                    'assets/restaurantes/gourmet_mirador1.jpg',
                    'assets/restaurantes/gourmet_mirador2.jpg',
                    'assets/restaurantes/gourmet_mirador3.jpg',
                    'assets/restaurantes/gourmet_mirador4.jpg',
                ]),
                'horario' => '10:00 - 22:00',
                'latitud' => -19.051271,
                'longitud' => -65.259781,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // ECONÓMICOS
            [
                'nombre' => 'Sabor Criollo',
                'descripcion' => 'Comida típica boliviana a precios accesibles.',
                'direccion' => 'Mercado Central',
                'precio' => 'bajo',
                'imagenAsset' => 'assets/restaurantes/sabor_criollo.jpg',
                'rating' => 4.3,
                'imagenes' => json_encode([
                    'assets/restaurantes/sabor_criollo1.jpg',
                    'assets/restaurantes/sabor_criollo2.jpg',
                    'assets/restaurantes/sabor_criollo3.jpg',
                    'assets/restaurantes/sabor_criollo4.jpg',
                ]),
                'horario' => '08:00 - 21:00',
                'latitud' => -19.048712,
                'longitud' => -65.259115,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pollos Rosita',
                'descripcion' => 'Pollo broaster crocante y al carbón, tradicional de Sucre, ideal para ir en familia o con amigos.',
                'direccion' => 'Frente de la Plazuela Zudañez',
                'precio' => 'bajo',
                'imagenAsset' => 'assets/restaurantes/rosita.jpg',
                'rating' => 4.4,
                'imagenes' => json_encode([
                    'assets/restaurantes/rosita1.jpg',
                    'assets/restaurantes/rosita2.jpg',
                    'assets/restaurantes/rosita3.jpg',
                    'assets/restaurantes/rosita4.jpg',
                ]),
                'horario' => '11:30 - 23:00',
                'latitud' => -19.047800,
                'longitud' => -65.260200,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Antojitos Doña Chela',
                'descripcion' => 'Comida casera típica con menú del día.',
                'direccion' => 'Av. Las Américas',
                'precio' => 'bajo',
                'imagenAsset' => 'assets/restaurantes/chela.jpg',
                'rating' => 4.4,
                'imagenes' => json_encode([
                    'assets/restaurantes/chela1.jpg',
                    'assets/restaurantes/chela2.jpg',
                    'assets/restaurantes/chela3.jpg',
                    'assets/restaurantes/chela4.jpg',
                ]),
                'horario' => '12:00 - 15:00',
                'latitud' => -19.042300,
                'longitud' => -65.259900,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Hamburguesas el Paceño',
                'descripcion' => 'Hamburguesas populares y económicas.',
                'direccion' => 'Zona Universitaria',
                'precio' => 'bajo',
                'imagenAsset' => 'assets/restaurantes/paceño.jpg',
                'rating' => 4.1,
                'imagenes' => json_encode([
                    'assets/restaurantes/paceño1.jpg',
                    'assets/restaurantes/paceño2.jpg',
                    'assets/restaurantes/paceño3.jpg',
                    'assets/restaurantes/paceño4.jpg',
                ]),
                'horario' => '18:00 - 23:00',
                'latitud' => -19.045200,
                'longitud' => -65.254300,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // POPULARES
            [
                'nombre' => 'El Patio',
                'descripcion' => 'Restaurante popular con comida variada y ambiente familiar.',
                'direccion' => 'Av. Las Américas',
                'precio' => 'medio',
                'imagenAsset' => 'assets/restaurantes/patio.jpg',
                'rating' => 4.5,
                'imagenes' => json_encode([
                    'assets/restaurantes/patio1.jpg',
                    'assets/restaurantes/patio2.jpg',
                    'assets/restaurantes/patio3.jpg',
                    'assets/restaurantes/patio4.jpg',
                ]),
                'horario' => '12:00 - 22:00',
                'latitud' => -19.042871,
                'longitud' => -65.259821,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pizzería Napoli',
                'descripcion' => 'Pizzas al horno de leña y pastas artesanales.',
                'direccion' => 'Zona Central',
                'precio' => 'medio',
                'imagenAsset' => 'assets/restaurantes/napoli.jpg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/restaurantes/napoli1.jpg',
                    'assets/restaurantes/napoli2.jpg',
                    'assets/restaurantes/napoli3.jpg',
                    'assets/restaurantes/napoli4.jpg',
                ]),
                'horario' => '12:00 - 23:00',
                'latitud' => -19.048910,
                'longitud' => -65.260701,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ==================== BARES ====================
        DB::table('bares')->insert([
            [
                'nombre' => 'GastroBar El Mercado',
                'descripcion' => 'Fusión gourmet con ingredientes frescos y carta de vinos premium.',
                'direccion' => 'Mercado Central, 2do nivel',
                'ambiente' => 'premium',
                'imagenAsset' => 'assets/bares/lounge360_4.jpg',
                'rating' => 4.7,
                'imagenes' => json_encode([
                    'assets/bares/lounge360_1.jpg',
                    'assets/bares/lounge360.jpg',
                    'assets/bares/terraza.jpg',
                    'assets/bares/skygarden.jpg',
                ]),
                'horario' => '11:00 - 22:00',
                'latitud' => -19.049101,
                'longitud' => -65.259007,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Lounge 360',
                'descripcion' => 'Bar lounge con vista panorámica, tragos premium y ambiente elegante.',
                'direccion' => 'Av. German Mendoza',
                'ambiente' => 'elegante',
                'imagenAsset' => 'assets/bares/lounge360.jpg',
                'rating' => 4.7,
                'imagenes' => json_encode([
                    'assets/bares/lounge360_1.jpg',
                    'assets/bares/lounge360_2.jpg',
                    'assets/bares/lounge360_3.jpg',
                    'assets/bares/lounge360_4.jpg',
                ]),
                'horario' => '18:00 - 02:00',
                'latitud' => -19.04623,
                'longitud' => -65.25910,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'La Terraza Sucre',
                'descripcion' => 'Ambiente elegante con coctelería de autor y vista nocturna.',
                'direccion' => 'Calle Bolívar',
                'ambiente' => 'premium',
                'imagenAsset' => 'assets/bares/terraza.jpg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/bares/terraza1.jpg',
                    'assets/bares/terraza2.jpg',
                    'assets/bares/terraza3.jpg',
                    'assets/bares/terraza4.jpg',
                ]),
                'horario' => '17:00 - 02:30',
                'latitud' => -19.04850,
                'longitud' => -65.25970,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Republic Lounge',
                'descripcion' => 'Cocktails internacionales y ambiente sofisticado.',
                'direccion' => 'Calle Loa 677',
                'ambiente' => 'elegante',
                'imagenAsset' => 'assets/bares/republic.jpeg',
                'rating' => 4.5,
                'imagenes' => json_encode([
                    'assets/bares/republic1.jpeg',
                    'assets/bares/republic2.jpeg',
                    'assets/bares/republic3.jpeg',
                    'assets/bares/republic4.jpeg',
                ]),
                'horario' => '19:00 - 02:00',
                'latitud' => -19.04710,
                'longitud' => -65.25940,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Mirador Bar Recoleta',
                'descripcion' => 'Bar con terraza y vista privilegiada a Sucre.',
                'direccion' => 'La Recoleta',
                'ambiente' => 'romántico',
                'imagenAsset' => 'assets/bares/recoleta.jpeg',
                'rating' => 4.7,
                'imagenes' => json_encode([
                    'assets/bares/recoleta1.jpeg',
                    'assets/bares/recoleta2.jpeg',
                    'assets/bares/recoleta3.jpeg',
                    'assets/bares/recoleta4.jpeg',
                ]),
                'horario' => '16:00 - 01:00',
                'latitud' => -19.05052,
                'longitud' => -65.25919,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'SkyBar Sucre',
                'descripcion' => 'Cocteles premium en altura con vista moderna.',
                'direccion' => 'Av. Las Américas',
                'ambiente' => 'skybar',
                'imagenAsset' => 'assets/bares/skybar.jpg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/bares/skybar1.jpg',
                    'assets/bares/skybar2.jpg',
                    'assets/bares/skybar3.jpg',
                    'assets/bares/skybar4.jpg',
                ]),
                'horario' => '18:00 - 03:00',
                'latitud' => -19.03450,
                'longitud' => -65.25300,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Luxury Bar Sucre',
                'descripcion' => 'Ambiente de lujo, música en vivo y vinos importados.',
                'direccion' => 'Zona Retiro',
                'ambiente' => 'luxury',
                'imagenAsset' => 'assets/bares/luxury.jpg',
                'rating' => 4.8,
                'imagenes' => json_encode([
                    'assets/bares/luxury1.jpg',
                    'assets/bares/luxury2.jpg',
                    'assets/bares/luxury3.jpg',
                    'assets/bares/luxury4.jpg',
                ]),
                'horario' => '18:00 - 02:00',
                'latitud' => -19.04231,
                'longitud' => -65.25981,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Pura Pura Bar & Grill',
                'descripcion' => 'Bar carne premium y tragos exclusivos.',
                'direccion' => 'Av. Marcelo Quiroga',
                'ambiente' => 'premium',
                'imagenAsset' => 'assets/bares/purapura.jpg',
                'rating' => 4.5,
                'imagenes' => json_encode([
                    'assets/bares/purapura1.jpg',
                    'assets/bares/purapura2.jpg',
                    'assets/bares/purapura3.jpg',
                    'assets/bares/purapura4.jpg',
                ]),
                'horario' => '17:00 - 01:00',
                'latitud' => -19.03682,
                'longitud' => -65.25221,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'SkyGarden Rooftop',
                'descripcion' => 'Bar en terraza con temática botánica y cocteles artesanales.',
                'direccion' => 'Zona Norte',
                'ambiente' => 'rooftop',
                'imagenAsset' => 'assets/bares/skygarden.jpg',
                'rating' => 4.7,
                'imagenes' => json_encode([
                    'assets/bares/skygarden1.jpg',
                    'assets/bares/skygarden2.jpg',
                    'assets/bares/skygarden3.jpg',
                    'assets/bares/skygarden4.jpg',
                ]),
                'horario' => '17:00 - 02:00',
                'latitud' => -19.03211,
                'longitud' => -65.25010,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Bellavista Bar',
                'descripcion' => 'Bar de ambiente refinado, vista nocturna y excelente mixología.',
                'direccion' => 'Zona Retiro Alto',
                'ambiente' => 'elegante',
                'imagenAsset' => 'assets/bares/bellavista.jpg',
                'rating' => 4.5,
                'imagenes' => json_encode([
                    'assets/bares/bellavista1.jpg',
                    'assets/bares/bellavista2.jpg',
                    'assets/bares/bellavista3.jpg',
                    'assets/bares/bellavista4.jpg',
                ]),
                'horario' => '18:30 - 02:00',
                'latitud' => -19.04185,
                'longitud' => -65.25872,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'La Esquina Bar',
                'descripcion' => 'Bar económico con música latina y ambiente juvenil.',
                'direccion' => 'Calle Aniceto Arce',
                'ambiente' => 'económico',
                'imagenAsset' => 'assets/bares/esquina.jpg',
                'rating' => 4.1,
                'imagenes' => json_encode([
                    'assets/bares/esquina1.jpg',
                    'assets/bares/esquina2.jpg',
                    'assets/bares/esquina3.jpg',
                    'assets/bares/esquina4.jpg',
                ]),
                'horario' => '18:00 - 01:00',
                'latitud' => -19.04712,
                'longitud' => -65.26084,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'La Taberna del Sur',
                'descripcion' => 'Bar tradicional con vinos nacionales y picadas.',
                'direccion' => 'Zona Sur',
                'ambiente' => 'tradicional',
                'imagenAsset' => 'assets/bares/taberna_sur.jpg',
                'rating' => 4.2,
                'imagenes' => json_encode([
                    'assets/bares/taberna1.jpg',
                    'assets/bares/taberna2.jpg',
                    'assets/bares/taberna3.jpg',
                    'assets/bares/taberna4.jpg',
                ]),
                'horario' => '17:00 - 00:30',
                'latitud' => -19.05500,
                'longitud' => -65.26600,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Joy Ride Café',
                'descripcion' => 'Uno de los bares más famosos de Sucre. Comida, tragos y música.',
                'direccion' => 'Calle Nicolás Ortiz',
                'ambiente' => 'popular',
                'imagenAsset' => 'assets/bares/joyride.jpg',
                'rating' => 4.6,
                'imagenes' => json_encode([
                    'assets/bares/joyride1.jpg',
                    'assets/bares/joyride2.jpg',
                    'assets/bares/joyride3.jpg',
                    'assets/bares/joyride4.jpg',
                ]),
                'horario' => '12:00 - 02:00',
                'latitud' => -19.04895,
                'longitud' => -65.25950,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'KulturCafe Berlin',
                'descripcion' => 'Bar cultural con eventos, bandas y bebidas artesanales.',
                'direccion' => 'Calle Avaroa',
                'ambiente' => 'popular',
                'imagenAsset' => 'assets/bares/kultur.jpg',
                'rating' => 4.7,
                'imagenes' => json_encode([
                    'assets/bares/kultur1.jpg',
                    'assets/bares/kultur2.jpg',
                    'assets/bares/kultur3.jpg',
                    'assets/bares/kultur4.jpg',
                ]),
                'horario' => '15:00 - 02:00',
                'latitud' => -19.04720,
                'longitud' => -65.26110,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ==================== FECHAS DESTACADAS (HITOS) ====================
        DB::table('fechas_destacadas')->insert([
            [
                'id' => 1,
                'titulo' => 'Festival de Danzas Folklóricas',
                'descripcion' => 'Muestra de danzas típicas de Chuquisaca y otras regiones de Bolivia, con énfasis en la cultura andina.',
                'icono' => '💃',
                'categoria' => 'Arte y Cultura',
                'fechaInicio' => '2025-11-28',
                'fechaFin' => '2025-12-01',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/danzas_festival.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'titulo' => 'Día contra la Violencia a la Mujer',
                'descripcion' => 'Actividades de concientización, ferias informativas y marchas pacíficas en el centro de la ciudad.',
                'icono' => '🎗️',
                'categoria' => 'Sociedad y Reivindicación',
                'fechaInicio' => '2025-11-25',
                'fechaFin' => '2025-11-25',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/mujer_violencia.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'titulo' => 'Navidad y Pesebres Gigantes',
                'descripcion' => 'Celebración de las fiestas de fin de año con pesebres, ferias navideñas y encuentros familiares. Duración: 20 al 31 de diciembre.',
                'icono' => '🎄',
                'categoria' => 'Festividades y Tradiciones',
                'fechaInicio' => '2025-12-20',
                'fechaFin' => '2025-12-31',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/feria_navidad.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'titulo' => 'Mercado Central Gastronómico',
                'descripcion' => 'Sabores típicos de Sucre disponibles todo el año en el Mercado Central: chorizos, mondongo, ají de fideo y más.',
                'icono' => '🍲',
                'categoria' => 'Gastronomía y Ferias',
                'fechaInicio' => '2025-01-01',
                'fechaFin' => '2025-12-31',
                'permanente' => 1,
                'imagenAsset' => 'assets/fechas/mercado.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'titulo' => '25 de Mayo – Primer Grito Libertario',
                'descripcion' => 'Conmemoración del Primer Grito Libertario de América en 1809, con actos cívicos, desfiles escolares, militares y actividades culturales en la ciudad de Sucre.',
                'icono' => '🏛️',
                'categoria' => 'Festividades y Tradiciones',
                'fechaInicio' => '2026-05-25',
                'fechaFin' => '2026-05-25',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/aniversario_sucre.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'titulo' => 'Festival Internacional de la Cultura (FIC)',
                'descripcion' => 'Muestra de arte, cine, teatro y música con participación nacional e internacional. Actividades en varios espacios culturales de Sucre.',
                'icono' => '🎨',
                'categoria' => 'Arte y Cultura',
                'fechaInicio' => '2026-06-10',
                'fechaFin' => '2026-06-14',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/fic_festival.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'titulo' => 'Carnaval de Sucre',
                'descripcion' => 'La festividad más colorida y alegre del año, con corsos, entradas y juegos de agua.',
                'icono' => '🎭',
                'categoria' => 'Festividades y Tradiciones',
                'fechaInicio' => '2026-02-10',
                'fechaFin' => '2026-02-18',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/carnaval.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'titulo' => 'Fiesta de la Virgen de Guadalupe',
                'descripcion' => 'La principal festividad religiosa de Sucre con misas, procesiones, entradas folclóricas y feria popular.',
                'icono' => '⛪',
                'categoria' => 'Festividades y Tradiciones',
                'fechaInicio' => '2026-09-08',
                'fechaFin' => '2026-09-10',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/guadalupe.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'titulo' => 'Feria de la Alasita Sucreña',
                'descripcion' => 'Feria tradicional de miniaturas y deseos, con enfoque en la abundancia, juegos y gastronomía.',
                'icono' => '🎁',
                'categoria' => 'Gastronomía y Ferias',
                'fechaInicio' => '2026-01-24',
                'fechaFin' => '2026-01-31',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/alasita.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'titulo' => 'Encuentro Nacional de Poesía',
                'descripcion' => 'Lecturas y talleres con poetas de todo el país, actividades en centros culturales y espacios públicos.',
                'icono' => '📚',
                'categoria' => 'Arte y Cultura',
                'fechaInicio' => '2026-04-15',
                'fechaFin' => '2026-04-18',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/poesia.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'titulo' => 'Día del Peatón',
                'descripcion' => 'Jornada sin vehículos motorizados, dedicada al deporte, el esparcimiento y actividades familiares en las avenidas principales.',
                'icono' => '🚴',
                'categoria' => 'Sociedad y Reivindicación',
                'fechaInicio' => '2025-09-01',
                'fechaFin' => '2025-09-01',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/peaton.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'titulo' => 'Semana Santa en Sucre',
                'descripcion' => 'Celebraciones religiosas, procesiones y actividades culturales durante la Semana Santa en el casco histórico.',
                'icono' => '✝️',
                'categoria' => 'Festividades y Tradiciones',
                'fechaInicio' => '2026-04-02',
                'fechaFin' => '2026-04-05',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/semana_santa.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 13,
                'titulo' => 'Festival del Chocolate Sucrense',
                'descripcion' => 'Feria dedicada al chocolate chuquisaqueño con degustaciones, talleres, concursos y ventas.',
                'icono' => '🍫',
                'categoria' => 'Gastronomía y Ferias',
                'fechaInicio' => '2026-07-10',
                'fechaFin' => '2026-07-14',
                'permanente' => 0,
                'imagenAsset' => 'assets/fechas/festival_chocolate.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ==================== EVENTOS RELACIONADOS ====================
        DB::table('eventos_relacionados')->insert([
            // HITO 1
            [
                'hitoId' => 1,
                'titulo' => 'Apertura y Desfile Inaugural',
                'descripcion' => 'Presentación de delegaciones nacionales e internacionales con trajes de gala.',
                'ubicacion' => 'Plaza 25 de Mayo, frente a la Catedral Metropolitana, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-11-30 17:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 1,
                'titulo' => 'Gala de la Cueca Chuquisaqueña',
                'descripcion' => 'Concurso y exhibición de la danza tradicional de Sucre.',
                'ubicacion' => 'Teatro Gran Mariscal, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-12-01 19:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 2
            [
                'hitoId' => 2,
                'titulo' => 'Marcha de Sensibilización',
                'descripcion' => 'Marcha pacífica con carteles y mensajes de reflexión contra la violencia de género.',
                'ubicacion' => 'Plaza 25 de Mayo, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-11-25 09:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 2,
                'titulo' => 'Feria Informativa y Talleres',
                'descripcion' => 'Puestos de instituciones y ONG con orientación legal, psicológica y material informativo.',
                'ubicacion' => 'Parque Simón Bolívar, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-11-25 15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 3
            [
                'hitoId' => 3,
                'titulo' => 'Inauguración de Pesebre Gigante',
                'descripcion' => 'Encendido de luces y apertura oficial del pesebre de la ciudad.',
                'ubicacion' => 'Parque Infantil, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-12-20 19:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 3,
                'titulo' => 'Misa de Gallo y Nochebuena',
                'descripcion' => 'Ceremonia religiosa principal de Nochebuena.',
                'ubicacion' => 'Catedral Metropolitana de Sucre, Plaza 25 de Mayo, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-12-24 22:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 3,
                'titulo' => 'Feria Navideña de Sucre',
                'descripcion' => 'Feria navideña con artesanías, juguetes, luces y puestos de comida típica.',
                'ubicacion' => 'Parque Multiproposito, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-12-21 18:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 3,
                'titulo' => 'Noche de Coros y Villancicos',
                'descripcion' => 'Presentación de coros navideños y grupos musicales locales al aire libre.',
                'ubicacion' => 'Plaza 25 de Mayo, frente a la Catedral, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-12-23 19:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 3,
                'titulo' => 'Feria Gastronómica Navideña',
                'descripcion' => 'Puestos de comida con buñuelos, api, picana y platos típicos de la temporada.',
                'ubicacion' => 'Zona ferial, alrededores del Estadio Patria, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-12-23 12:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 4
            [
                'hitoId' => 4,
                'titulo' => 'Día de la Picana Navideña',
                'descripcion' => 'Promoción especial de picana y platos de Año Nuevo.',
                'ubicacion' => 'Mercado Central, sección comidas, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-01-01 12:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 4,
                'titulo' => 'Taller de preparación de chorizos chuquisaqueños',
                'descripcion' => 'Aprende a preparar chorizos con expertos cocineros del mercado.',
                'ubicacion' => 'Mercado Central, piso 2, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-01-15 10:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 5
            [
                'hitoId' => 5,
                'titulo' => 'Sesión de Honor en la Casa de la Libertad',
                'descripcion' => 'Acto cívico central con autoridades locales y departamentales.',
                'ubicacion' => 'Casa de la Libertad, Plaza 25 de Mayo, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-05-25 09:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 5,
                'titulo' => 'Desfile Cívico Escolar y Militar',
                'descripcion' => 'Desfile con unidades educativas, organizaciones e instituciones armadas.',
                'ubicacion' => 'Plaza 25 de Mayo y Av. de las Américas, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-05-25 10:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 6
            [
                'hitoId' => 6,
                'titulo' => 'Muestra de Cine Boliviano',
                'descripcion' => 'Proyección de películas nacionales con conversatorios posteriores.',
                'ubicacion' => 'Centro Cultural Universitario, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-06-11 18:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 6,
                'titulo' => 'Concierto de Clausura FIC',
                'descripcion' => 'Presentación de bandas y artistas invitados en un concierto al aire libre.',
                'ubicacion' => 'Teatro Gran Mariscal, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-06-14 20:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 7
            [
                'hitoId' => 7,
                'titulo' => 'Elección y Coronación de la Reina del Carnaval',
                'descripcion' => 'Evento de gala con presentación de candidatas y fiesta de apertura.',
                'ubicacion' => 'Coliseo Jorge Revilla Aldana, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-02-10 20:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 7,
                'titulo' => 'Entrada Folklórica del Carnaval',
                'descripcion' => 'El evento central con comparsas, bandas y disfraces tradicionales.',
                'ubicacion' => 'Av. Hernando Siles, recorrido central del Carnaval, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-02-14 14:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 8
            [
                'hitoId' => 8,
                'titulo' => 'Procesión y desfile de carros alegóricos',
                'descripcion' => 'La procesión más importante de la ciudad, con participación masiva de fieles.',
                'ubicacion' => 'Desde la Catedral Metropolitana hasta La Recoleta, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-09-08 15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 8,
                'titulo' => 'Feria popular de comida y música',
                'descripcion' => 'Stands de comida tradicional, juegos y música en vivo.',
                'ubicacion' => 'Zona Estadio Patria, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-09-09 10:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 9
            [
                'hitoId' => 9,
                'titulo' => 'Inauguración de la feria y bendición',
                'descripcion' => 'Apertura oficial con ritos de bendición a las miniaturas y discursos.',
                'ubicacion' => 'Campo Ferial Multipropósito, zona Max Toledo, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-01-24 11:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 9,
                'titulo' => 'Venta de platos típicos a miniatura',
                'descripcion' => 'Platos tradicionales vendidos en tamaño miniatura para rituales de prosperidad.',
                'ubicacion' => 'Sector gastronómico, Campo Ferial Multipropósito, zona Max Toledo, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-01-27 12:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 10
            [
                'hitoId' => 10,
                'titulo' => 'Taller de métrica y verso clásico',
                'descripcion' => 'Taller dirigido a jóvenes escritores en el Centro Cultural Universitario.',
                'ubicacion' => 'Centro Cultural Universitario, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-04-16 15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 10,
                'titulo' => 'Recital poético central (abierto al público)',
                'descripcion' => 'Lecturas centrales con poetas invitados de renombre.',
                'ubicacion' => 'Casa de la Cultura, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-04-17 19:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 11
            [
                'hitoId' => 11,
                'titulo' => 'Ciclovía recreativa',
                'descripcion' => 'Espacios habilitados para bicicletas, patines y caminatas familiares.',
                'ubicacion' => 'Av. de las Américas, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-09-01 09:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 11,
                'titulo' => 'Feria de salud y deportes',
                'descripcion' => 'Actividades deportivas, chequeos médicos básicos y juegos para niños.',
                'ubicacion' => 'Plaza 25 de Mayo, Sucre, Bolivia',
                'fechaHoraInicio' => '2025-09-01 10:30:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 12
            [
                'hitoId' => 12,
                'titulo' => 'Procesión del Viernes Santo',
                'descripcion' => 'Procesión principal con recorrido por el centro histórico de Sucre.',
                'ubicacion' => 'Centro histórico, Plaza 25 de Mayo y alrededores, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-04-03 18:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 12,
                'titulo' => 'Vía Crucis juvenil',
                'descripcion' => 'Recorrido juvenil con meditaciones en diferentes puntos de la ciudad.',
                'ubicacion' => 'Desde la Catedral Metropolitana hasta La Recoleta, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-04-04 09:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // HITO 13
            [
                'hitoId' => 13,
                'titulo' => 'Inauguración del Festival del Chocolate',
                'descripcion' => 'Apertura oficial con exposición de marcas locales de chocolate.',
                'ubicacion' => 'Centro Cultural Universitario, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-07-10 10:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hitoId' => 13,
                'titulo' => 'Taller de bombones artesanales',
                'descripcion' => 'Taller práctico para aprender a hacer bombones con chocolate sucrense.',
                'ubicacion' => 'Casa de la Cultura, Sucre, Bolivia',
                'fechaHoraInicio' => '2026-07-11 15:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
